### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by cryptoknightsz** [qt333/MemHashAuto#1]
![image](https://github.com/user-attachments/assets/089efc4f-79aa-443f-aa0e-c8d02ab1bc32)
It's stuck here

**Comment by qt333** [comment]
> ![image](https://github.com/user-attachments/assets/089efc4f-79aa-443f-aa0e-c8d02ab1bc32)
> It's stuck here 

I should have opened Memhash app telegram window

*It only supports Windows OS

Also have u installed all dependencies?

**Comment by cryptoknightsz** [comment]
I have memhash window opened ser and yes i've installed all dependencies (i tried using it with tg desktop and portable versions)

**Comment by qt333** [comment]
did u start script with full enegry? if not - he will wait till enegry is full

btw, i already made an update, so the script will start with partial energy restored bar, check it out and make a feedback for any issue

**Comment by cryptoknightsz** [comment]
It's good, but when I slept while running the script, I noticed one thing: my balance only increased by 10. However, the log shows that the script ran many times. Additionally, when I looked into the script, it showed 'Waiting for energy restore,' but I checked the mini-app and it was already full. This is probably a bug or something, so please look into it.

**Comment by cryptoknightsz** [comment]
![image](https://github.com/user-attachments/assets/8cbe217b-ea9d-4af5-868d-7187cd3a4892)
It's same again, not working
my energy bar was full still it didn't started the mining

**Comment by cryptoknightsz** [comment]
Kindly look into this

**Comment by cryptoknightsz** [comment]
UPD: Still same issue

**Comment by cryptoknightsz** [comment]
![image](https://github.com/user-attachments/assets/21af2255-74e1-4cf8-b1bf-5ab5e2f610e5)
One more bug, it says stopped but bot continues running

**Comment by qt333** [comment]
> It's same again, not working
> my energy bar was full still it didn't started the mining

This should be fixed in the recent update, I have noticed wrong logic in a code with logger message

**Comment by qt333** [comment]
> One more bug, it says stopped but bot continues running

Looks like the script fails to click the button when the condition is met. Hm

On my PC all work fine idk

Make sure you didn't resize the tg window or cover it with another one OR maybe interrupt it with the mouse move so the click was missed...

**Comment by qt333** [comment]
Wait till 50% of the energy is restored,  and then launch the script. If the click still won't work I'll make a debug version so we can see what is a problem
